#!/usr/bin/env ruby

msfile = ARGV[0]

n = 0
m = 0
lines = Array.new
lines = File.readlines(msfile)
n = lines.size - 1
m = lines[0].size


puts "#{n} #{m}"
puts " "
lines.each do |line|
  puts line.split('').join(' ') 
end
